<a href="https://colab.research.google.com/github/Ammulator/Few-Operations-on-Dataset/blob/main/Operations_on_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd


In [5]:
df=pd.read_csv("sample_data/california_housing_train.csv")
#For Selecting Single Column
col=df['total_rooms']
print(col)

0        5612.0
1        7650.0
2         720.0
3        1501.0
4        1454.0
          ...  
16995    2217.0
16996    2349.0
16997    2677.0
16998    2672.0
16999    1820.0
Name: total_rooms, Length: 17000, dtype: float64


In [7]:
#For Selecting Multiple Columns
mcol=df[['housing_median_age','total_bedrooms','households']]
print(mcol.head())

   housing_median_age  total_bedrooms  households
0                15.0          1283.0       472.0
1                19.0          1901.0       463.0
2                17.0           174.0       117.0
3                14.0           337.0       226.0
4                20.0           326.0       262.0


In [9]:
#Creating New columns
df['Rooms']=df['total_rooms']== 812
print(df.head())

   longitude  latitude  ...  median_house_value  Rooms
0    -114.31     34.19  ...             66900.0  False
1    -114.47     34.40  ...             80100.0  False
2    -114.56     33.69  ...             85700.0  False
3    -114.57     33.64  ...             73400.0  False
4    -114.57     33.57  ...             65500.0  False

[5 rows x 10 columns]


In [11]:
#Converting Pandas Series to Numpy Array
arr=df['total_rooms'].values
print(arr)

[5612. 7650.  720. ... 2677. 2672. 1820.]


In [15]:
#Converting Pandas Dataframe to Numpy Array
arr1=df[['latitude','longitude']].values
print(arr1)

[[  34.19 -114.31]
 [  34.4  -114.47]
 [  33.69 -114.56]
 ...
 [  41.84 -124.3 ]
 [  41.8  -124.3 ]
 [  40.54 -124.35]]


In [19]:
#Masking- Selecting row with certain criteria
arr=df[['latitude','total_rooms','housing_median_age']].values[:20]
#Housing_median_age Lower than 18
mask=arr[:,2]<18
print(mask)
print("\n\n")
print(arr[mask])
print("\n\n")
print("\n\n")
#For shotcut for calculating greator than 18
print(arr[arr[:,2]>18])

[ True False  True  True False False False False False False  True False
 False False  True  True False False  True  True]



[[  34.19 5612.     15.  ]
 [  33.69  720.     17.  ]
 [  33.64 1501.     14.  ]
 [  33.62 3741.     16.  ]
 [  32.76 1448.     15.  ]
 [  34.89 2556.     17.  ]
 [  32.74 1388.     17.  ]
 [  33.92   97.     17.  ]]






[[  34.4  7650.     19.  ]
 [  33.57 1454.     20.  ]
 [  33.63 1387.     29.  ]
 [  33.61 2907.     25.  ]
 [  34.83  812.     41.  ]
 [  33.61 4789.     34.  ]
 [  34.83 1497.     46.  ]
 [  33.6  1988.     21.  ]
 [  34.84 1291.     48.  ]
 [  34.83 2478.     31.  ]
 [  33.6  1678.     28.  ]
 [  32.79   44.     21.  ]]


In [24]:
#Summing and Counting of Above value
print(mask.sum())
#or
print((arr[:,2]<18).sum())

8
8


In [27]:
import numpy as np
import pandas as pd
filename = input("Enter the file name:")
df=pd.read_csv(filename)
print(df.head())
column_name = input("Enter the column name:")
a=df[column_name].values
print(a)


Enter the file name:sample_data/california_housing_train.csv
   longitude  latitude  ...  median_income  median_house_value
0    -114.31     34.19  ...         1.4936             66900.0
1    -114.47     34.40  ...         1.8200             80100.0
2    -114.56     33.69  ...         1.6509             85700.0
3    -114.57     33.64  ...         3.1917             73400.0
4    -114.57     33.57  ...         1.9250             65500.0

[5 rows x 9 columns]
Enter the column name:longitude
[-114.31 -114.47 -114.56 ... -124.3  -124.3  -124.35]
